import type {Review,ReviewContext} from './populationReview'
export interface Segment {id:string;filename:string;sha256:string;activity_id:string|null;group:string;label:string;duration_seconds:number;samples:number;signals:string[];warnings:string[];kind?:'activity'|'segment';quality?:{missing_power_samples:number;missing_hr_samples:number;gap_count:number}|null}
export interface Split {id:string;unit:string;seed:number;percentages:number[];assignments:Record<string,string[]>;actual_percentages:number[];warnings:string[]}
export interface Dataset {id:string;name:string;created_at:string;segments:Segment[];stats:{count:number;duration_mean:number;duration_sd:number|null};split:Split|null;filters:unknown}
export interface Config {lower:number[];upper:(number|null|string)[];n_starts:number;seed:number;max_nfev:number;[key:string]:unknown}
export interface Structure {id:string;name:string;parameters:{key:string;unit:string}[];default_config:Config}
export interface Model {id:string;version:string;name:string;equation:string;initial_conditions:string;parameters:{key:string;unit:string}[];default_config:Config;structures?:Structure[]}
export interface Run {id:string;manifest_filename:string;created_at:string;status:string;dataset:Dataset;split:Split;model:Model;config:Config;signal:string;columns:string[];progress:{done:number;total:number;failed:number};error?:string;code_changed_since_original?:boolean;environment:{code_sha256:string};archived_at?:string}
export interface Estimate {estimate:number;se:number|null;ci95:[number,number]|null;rse_pct:number|null;at_bound:boolean;near_bound?:boolean;fixed?:boolean}
export interface PopulationConfig {prediction_mode?:"legacy_power_only"|"observed_hr"|"local_B_10s";max_rse_pct:number;max_correlation:number;exclude_near_bounds:boolean;draws:number;seed:number}
export interface PopulationFitCorrelations {fit_correlations?:Record<string,{n:number;matrix:(number|null)[][]|null}>}
export interface PopulationStats {n:number;values:number[];mean:number|null;median:number|null;sd:number|null;qq:{theoretical:number[];observed:number[]}}
export interface PopulationPrediction {equilibrium_B?:number;evaluation_start_s?:number;calibration?:{B_se_conditional:number;warnings:string[];samples:number}|null;segment_id:string;filename:string;activity_id?:string;status:string;error?:string;P0:number;initial_HR:number;missing_hr:number;gaussian_domain_acceptance:number;band_available:boolean;metrics:Record<string,number|null>|null;series:{time:number[];power:number[];observed:(number|null)[];predicted:number[];residual:(number|null)[];lower:number[];upper:number[]}}
export interface Population {reviews?:Record<string,Review>;review_context?:ReviewContext;id:string;version:string;created_at:string;status:string;reason?:string;config:PopulationConfig;train_count:number;retained_vectors:number;minimum_vectors?:number;parameters:{key:string;unit:string}[];warnings:string[];distributions:Record<string,{all:PopulationStats;retained:PopulationStats}>;screening:{segment_id:string;included:boolean;parameters:Record<string,string[]>;fit_warnings:string[]}[];model:null|{keys:string[];mean:number[];sd:number[];mean_ci95:number[][];covariance:number[][];correlation:(number|null)[][];observed_correlation:(number|null)[][];fixed:boolean[]};test:PopulationPrediction[]}
export interface Fit {segment_id:string;filename:string;status:string;error?:string;optimizer_success?:boolean|null;identification_valid?:boolean;failure_reasons?:string[];parameters:Record<string,Estimate>;metrics:Record<string,number|null>;warnings:string[];optimizer:{success:boolean;status:number;message:string;nfev:number};uncertainty:{rank:number;p?:number;jacobian_condition:number|null};all_starts_agree:boolean;starts:unknown[];series?:{time:number[];power:number[];observed:number[];predicted:number[];residual:number[]};rho?:number|null;model_structure?:string;pre_window?:{included_in_objective?:boolean;available:boolean;used:boolean;samples:number;time:number[];power:(number|null)[];observed:(number|null)[]};residual_acf?:{lags:number[];values:(number|null)[]};identifiability?:{correlations:Record<string,number|null>;correlation_K_tau:number|null};initialization_mode?:string;search?:{strategy:string;baseline_SSE:number;selected_source:string;grid_evaluations:number};initial_conditions?:{P0:number;HR0:number;B?:number;x0?:number}}
